### ISSUE TITLE
Padding should be done in Squeeze not in Absorb

### ISSUE THREAD

**Issue by shufps** [Troikahash/reference#2]
I'm not sure if this is a bug or it is intended as it is ...

Absorbing shouldn't do any padding because it should be possible - like SHA3 for instance - to absorb multiple blocks of data which can be smaller than the block size without applying padding to each block.
SHA3 keeps the rest of data if the data to absorb is less than the block size and does padding with the rest in the final squeeze.

If implemented right, there should be no difference in the result if doing one absorb with a large block vs doing a lot of smaller absorbs.

Should I fix it and do a merge request?

(in case of IOTA library compatibility there are some cases where a hash-context is reinitialized by absorbing one block as starting point for the further absorbs, but this is not possible how it's implemented here because after the first block padding is applied; Collecting data for a single big absorb needs unnecessarily much memory. So I think padding should be done in squeeze when it is sure no absorb followes.)

**Comment by ewti** [comment]
The idea of this reference implementation is to be as simple and pedagogical as possible: one (complete) message - one hash value.  It is not intended for any production purposes.

One could indeed implement such a 'streaming' interface as you described - although we would ideally have that in another implementation.

**Comment by shufps** [comment]
Ok, sorry ... I thought it was a bug because it shouldn't make a difference if one single absorb + squeeze or multiple smaller absorbs which squeeze are done. At least the reference implementation of sha3 does it this way ;-) But I understand your point.

**Comment by ghost** [comment]
creatinng your own is the thing, finalize is the function
